### ISSUE TITLE
CSS is not responsive

### ISSUE THREAD

**Issue by amkhrjee** [aniruddh-mukherjee/game-story#1]
The design implemented in the current state is a mixture of Bootstrap, Reactstap and core CSS. The website does not perform well in smaller screen sizes.

**Comment by veekay21** [comment]
I can help. 
Give a green light so I can start working on it :)

**Comment by amkhrjee** [comment]
Sure. It has 350+ lines of CSS. It would be great if you could look into the Navbar and footer part and help fix them.
